url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "https://dannehess.github.io/jekyllportfolio/" # the subpath of your site, e.g. /blog
title: "Daniel Hessling" # the name of your site, e.g. ACME Corp.